### ISSUE TITLE
NoClassDefFoundError- com/googlecode/mp4parser/util/Matrix

### ISSUE THREAD

**Issue by fenomeno** [AbedElazizShe/LightCompressor#126]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/googlecode/mp4parser/util/Matrix;
        at com.abedelazizshe.lightcompressorlibrary.video.Mp4Movie.<init>(Mp4Movie.kt:11)
        at com.abedelazizshe.lightcompressorlibrary.utils.CompressorUtils.setUpMP4Movie(CompressorUtils.kt:54)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.start(Compressor.kt:174)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.access$start(Compressor.kt:30)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor$compressVideo$2.invokeSuspend(Compressor.kt:134)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor$compressVideo$2.invoke(Unknown Source:8)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor$compressVideo$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.compressVideo(Compressor.kt:53)
        at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:142)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4654e64, Dispatchers.Main]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.googlecode.mp4parser.util.Matrix" on path: DexPathList[[zip file "/data/app/~~KpcBHB0AfIqG45Z-kxbOTg==/abcd-kXDFim5u9HESaNKDIOVMoA==/base.apk"],nativeLibraryDirectories=[/data/app/~~KpcBHB0AfIqG45Z-kxbOTg==/abcd-kXDFim5u9HESaNKDIOVMoA==/lib/arm64, /data/app/~~KpcBHB0AfIqG45Z-kxbOTg==/abcd-kXDFim5u9HESaNKDIOVMoA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 18 more

**Comment by perez-alex** [comment]
add to your dependencies. Don't update the version of this lib, this is the only one that doesn't corrupt audio on video compression

implementation ('com.googlecode.mp4parser:isoparser:1.0.6'){ 
        exclude group: 'org.aspectj', module: 'aspectjrt'
    }
