### ISSUE TITLE
MediaCodec configure error

### ISSUE THREAD

**Issue by joelpjy** [AbedElazizShe/LightCompressor#159]
Device: Google Pixel 4XL
OS: Android 12, API 32
LightCompressor Version used: 1.3.0

Issue:
Im getting an error with the MediaCodec when compressing a screen recording on Google Pixel 4XL.
When it happens, it creates a corrupted file of size 28B and it calls the onSuccess.

I tried compressing a video taken from the camera and it works fine.
I tried on other android devices (Android 10), both screen recordings and  video from camera is working.

```
An error has occurred!
java.lang.IllegalArgumentException
    at android.media.MediaCodec.native_configure(Native Method)
    at android.media.MediaCodec.configure(MediaCodec.java:2176)
    at android.media.MediaCodec.configure(MediaCodec.java:2092)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.prepareEncoder(Compressor.kt:516)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.start(Compressor.kt:199)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.access$start(Compressor.kt:30)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor$compressVideo$2.invokeSuspend(Compressor.kt:134)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor$compressVideo$2.invoke(Unknown Source:8)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor$compressVideo$2.invoke(Unknown Source:4)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
    at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.compressVideo(Compressor.kt:53)
    at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:180)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by AbedElazizShe** [comment]
Hi @joelpjy, thank you for opening this issue. Could you please share the video with me? I have pixel 2XL and pixel 4A, both are working fine. I could not manage to screen record pixel 4XL.

Thank you.

**Comment by joelpjy** [comment]
hello @AbedElazizShe , sry for the late reply.

Heres the video: https://drive.google.com/file/d/1ZMRqhUtj1mVWM4CXgbU6fMCNiIZp5bey/view?usp=sharing

**Comment by AbedElazizShe** [comment]
Hi @joelpjy I believe the issue is fixed in the new release. Will post is shortly.
