### ISSUE TITLE
rocess: com.pol.poliub, PID: 29682     java.lang.AssertionError: Assertion failed

### ISSUE THREAD

**Issue by Jahnzeb** [AbedElazizShe/LightCompressor#160]
@AbedElazizShe i am getting this issue.. can you please help me?

**Comment by AbedElazizShe** [comment]
@Jahnzeb please provide more information. Maybe a screenshot of the log?

**Comment by alexbusuioc** [comment]
I was getting the same error. **Line 77 in VideoCompressor.kt** - `assert(configureWith.videoNames.size == uris.size)`

I fixed it by passing the same length for the two lists - `configureWith/videoNames`  and `uris`

**Comment by VishV-Android** [comment]
Getting this Error,

`FATAL EXCEPTION: main
                                               Process: com.nt.tvcastproj, PID: 6315
                                               java.lang.AssertionError: Assertion failed
                                               	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor.start(VideoCompressor.kt:77)
                                               	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor.start$default(VideoCompressor.kt:66)
                                               	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor.start(Unknown Source:31)
                                               	at com.nt.CastDemoProject.VideoCompressorManager.startCompression(VideoCompressorManager.java:18)
                                               	at com.nt.CastDemoProject.MainActivity.onActivityResult(MainActivity.java:250)
                                               	at android.app.Activity.dispatchActivityResult(Activity.java:8951)
                                               	at android.app.ActivityThread.deliverResults(ActivityThread.java:5987)
                                               	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6033)
                                               	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
                                               	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                               	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                               	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                               	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
                                               	at android.os.Handler.dispatchMessage(Handler.java:106)
                                               	at android.os.Looper.loopOnce(Looper.java:226)
                                               	at android.os.Looper.loop(Looper.java:313)
                                               	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                               	at java.lang.reflect.Method.invoke(Native Method)
                                               	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                               	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`
