### ISSUE TITLE
RuntimeException: setDataSource failed

### ISSUE THREAD

**Issue by ShaQib07** [AbedElazizShe/LightCompressor#68]
Fatal Exception: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:81)
       at com.abedelazizshe.lightcompressorlibrary.Compressor.compressVideo(Compressor.kt:45)
       at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:97)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by AbedElazizShe** [comment]
@ShaQib07 Thank you for opening this issue, please provide more details to undertsand how this is happening:

- The device's model and the Android version.
- The version of the library used.
- Sample code/link to show the method you used to pick the video and send its path to the library. 

Thank you.

**Comment by ShaQib07** [comment]
Thanks for your reply.
Here's the information you've asked for
Android OS :  9 | Device : Galaxy S9
Library Version = 0.7.7

`fun downloadVideo() {
        val fileExists = findVideoFile(context, getPublicVideoFileName())
        Timber.d("GSK | $fileExists")
        if (fileExists) {
            videoDownloadLiveData.postValue(Resource.Success(context.getString(R.string.file_already_exists)))
        } else {
            val mediaData = messageData?.message?.media
            mediaData?.getContentTemporaryUrl(object : CallbackListener<String>() {
                override fun onSuccess(url: String?) {
                    url?.let {
                        val outputFile = File(getOutputDirectory(), getLocalVideoFileName())
                        viewModelScope.launch(Dispatchers.IO) {
                            try {
                                Timber.d("GSK | Started")
                                videoDownloadLiveData.postValue(Resource.Loading())
                                val downloadingUrl = URL(it)
                                val urlConnection: URLConnection = URL(it).openConnection()
                                val contentLength: Int = urlConnection.contentLength
                                val stream = DataInputStream(downloadingUrl.openStream())
                                val buffer = ByteArray(contentLength)
                                stream.readFully(buffer)
                                stream.close()
                                val fos = DataOutputStream(FileOutputStream(outputFile))
                                fos.apply {
                                    write(buffer)
                                    flush()
                                    close()
                                }
                                val div = outputFile.length().div(1024 * 1024)
                                Timber.d("GSK | Closed - Compressing | $div")
                                compress(outputFile)
                            } catch (e: Exception) {
                                Timber.d("Downloading failed $e")
                                videoDownloadLiveData.postValue(Resource.Error(e))
                            }
                        }
                    }
                }
            })
        }
    }`
    
    `private fun compress(sourceFile: File) {
        viewModelScope.launch {
            val compressedFile = File(getOutputDirectory(), getPublicVideoFileName())
            VideoCompressor.start(
                sourceFile.absolutePath,
                compressedFile.absolutePath,
                object : CompressionListener {
                    override fun onProgress(percent: Float) {}

                    override fun onStart() {}

                    override fun onSuccess() {
                        writeVideoFileIntoPublicDirectory(compressedFile, sourceFile)
                    }

                    override fun onFailure(failureMessage: String) {
                        videoDownloadLiveData.postValue(Resource.Error(Throwable(failureMessage)))
                    }

                    override fun onCancelled() {
                        videoDownloadLiveData.postValue(Resource.Error(Throwable("Cancelled")))
                    }

                },
                VideoQuality.VERY_HIGH,
                isMinBitRateEnabled = false,
                keepOriginalResolution = false
            )
        }
    }`

**Comment by AbedElazizShe** [comment]
@ShaQib07 thank you for the details and sorry for the late reply. Could you please try to use the latest version of the library ?

**Comment by soelling** [comment]
@AbedElazizShe I have reproduced the same issue on following device:
Android OS: 7.0
Device: Samsung Galaxy XCover
Library Version: 0.9

**Comment by ShaQib07** [comment]
@AbedElazizShe sorry, currently working on something else, but I'll surely get back to it later and let you know.

**Comment by AbedElazizShe** [comment]
@soelling @ShaQib07 thank you for yor replies. I tested version 0.9.2 on the mentioned devices and i didn't have any issues. Could you please try the sample app and let me know if you're having the same issue?

**Comment by deepakjain1989** [comment]
@AbedElazizShe I have reproduced the same issue on following device:
Android OS:  android11
Device: Mi A3
Library Version:1.2.2

**Comment by qsdigor** [comment]
@AbedElazizShe Hi, I have implemented this library and have the same error on the Xiaomi Redmi Note 11 only on one wmv format video. 

This is my implementation.
```
        val uris = listOf(uri)
        VideoCompressor.start(
            context = applicationContext,
            uris = uris,
            isStreamable = false,
            appSpecificStorageConfiguration = AppSpecificStorageConfiguration(
                subFolderName = "compressed-videos"
            ),
            configureWith = Configuration(
                videoNames = uris.map { uri -> uri.pathSegments.last() }, /*list of video names, the size should be similar to the passed uris*/
                quality = VideoQuality.MEDIUM,
                isMinBitrateCheckEnabled = true,
                videoBitrateInMbps = 5,
            ),
            listener = object : CompressionListener {
                override fun onProgress(index: Int, percent: Float) {
                    Timber.d("Compression progress: $percent")
                    if (percent <= 100) {
                        setForegroundAsync(createCompressForegroundInfo(percent.toInt()))
                    }
                }

                override fun onStart(index: Int) {
                    Timber.d("Compression started: ${uri.path}")
                    setForegroundAsync(createCompressForegroundInfo(0))
                }

                override fun onSuccess(index: Int, size: Long, path: String?) {
                    Timber.d("Compressed video path: $path")
                    val compressedFile = File(path)
                    val intentUri = androidx.core.content.FileProvider.getUriForFile(
                        applicationContext,
                        applicationContext.packageName + ".provider",
                        compressedFile
                    )

                    onVideoCompressed.invoke(intentUri)
                }

                override fun onFailure(index: Int, failureMessage: String) {
                    Timber.d("Compression failed: $failureMessage")
                    onVideoCompressed.invoke(uri)
                }

                override fun onCancelled(index: Int) {
                    Timber.d("Compression cancelled")
                    onVideoCompressed.invoke(uri)
                }
            }
        )
```


This is my stacktrace.

```
 java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{1aff5d5 16162:com.opendrive.android/u0a461} (pid=16162, uid=10461) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
                                                     	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
                                                     	at android.os.Parcel.createException(Parcel.java:2410)
                                                     	at android.os.Parcel.readException(Parcel.java:2393)
                                                     	at android.os.Parcel.readException(Parcel.java:2335)
                                                     	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6097)
                                                     	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7415)
                                                     	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3363)
                                                     	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2529)
                                                     	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2013)
                                                     	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
                                                     	at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
                                                     	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor.getMediaPath(VideoCompressor.kt:369)
                                                     	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor.access$getMediaPath(VideoCompressor.kt:27)
                                                     	at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$doVideoCompression$1$job$1.invokeSuspend(VideoCompressor.kt:113)
                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                     	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                     	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                                                     	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2317590, Dispatchers.IO]
```
