### ISSUE TITLE
compression is slow

### ISSUE THREAD

**Issue by shaktis110** [AbedElazizShe/LightCompressor#88]
hello sir 

device - realme xmax pro ram 6gb.

tested with demo application.

platform - android 8, android 9 , android 10, android 11

Thanks for this wonderful project. I am using this library in production chat application.
One thing I noticed is that the compression is slow in the actual device. It takes about 15-20 seconds for compression of 5-10 MB files. I have also downloaded the demo app and its working almost as mentioned above.
Is there any way to speed up the compression.

I am not expert in java can it help to improve compression speed?

https://stackoverflow.com/questions/35884600/android-mediacodec-encode-and-decode-in-asynchronous-mode/35885471#35885471

https://github.com/mstorsjo/android-decodeencodetest

thanks for your precious time.

**Comment by shaktis110** [comment]
sir i am not expert in java but i found some resources which can be useful for compression speed

https://stackoverflow.com/questions/35884600/android-mediacodec-encode-and-decode-in-asynchronous-mode/35885471#35885471
https://github.com/mstorsjo/android-decodeencodetest

**Comment by AbedElazizShe** [comment]
@shaktis110 thank you for opening this issue and sorry for the late reply. I have improved the speed and I will release a new verion most probably tomorrow. 

![lc1](https://user-images.githubusercontent.com/20614470/131521322-01ed9130-ab1a-4060-bee5-544ebc2ffa78.PNG)
![lc2](https://user-images.githubusercontent.com/20614470/131521329-97841285-cdc3-442f-ae68-23bae3b4f513.PNG)
![lc3](https://user-images.githubusercontent.com/20614470/131521331-8fc1df77-f917-4dc9-8120-f32846478615.PNG)

**Comment by shaktis110** [comment]
thank you so much sir

**Comment by AbedElazizShe** [comment]
@shaktis110 please try version 0.9.7 and let me know if it's working as expected. Thank you.

**Comment by shaktis110** [comment]
respected sir new release version is not working .
in log cat 
android.media.MediaCodec$CodecException: Error 0xffffffc3

**Comment by AbedElazizShe** [comment]
Can you please share the error log on the physical device? Emulators are expected not to work due to the lack of hardware encoders.

**Comment by shaktis110** [comment]
hello sir

here is the log from physical device - realme max pro

2021-09-02 11:04:27.915 10538-12191/com.abedelazizshe.lightcompressor D/ACodec: AllocateComponent OMX.MTK.VIDEO.ENCODER.AVC success
2021-09-02 11:04:27.915 10538-12191/com.abedelazizshe.lightcompressor D/ACodec: [OMX.MTK.VIDEO.ENCODER.AVC] Now Loaded
2021-09-02 11:04:27.918 10538-11172/com.abedelazizshe.lightcompressor E/Compressor: Error 0xffffffc3
    android.media.MediaCodec$CodecException: Error 0xffffffc3
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2127)
        at android.media.MediaCodec.configure(MediaCodec.java:2043)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.prepareEncoder(Compressor.kt:495)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.start(Compressor.kt:207)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.compressVideo(Compressor.kt:160)
        at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:114)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-09-02 11:04:27.980 10538-11172/com.abedelazizshe.lightcompressor E/StreamableVideo: last atom in file was not a moov atom

**Comment by AbedElazizShe** [comment]
Thank you for the details, you can keep using the old version of the library until I fix this later today.

**Comment by shaktis110** [comment]
Great, thanks sir !

**Comment by AbedElazizShe** [comment]
It was unsupported codec profile, fixed in 0.9.8. Thank you.

**Comment by shaktis110** [comment]
I have tested and it is working perfectly fine with better speed

Thank you very much sir you are a blessing.
