### ISSUE TITLE
Compression is Success but generated video is not working

### ISSUE THREAD

**Issue by vedraj360** [AbedElazizShe/LightCompressor#93]
Compression is Success but generated video is not working

Getting null pointer exception, using android emulator.

Here is the error message 

2021-09-15 20:10:28.411 18517-19821/in.app.dev E/Compressor: An error has occurred!
    java.lang.NullPointerException
        at com.abedelazizshe.lightcompressorlibrary.video.Track.<init>(Track.kt:248)
        at com.abedelazizshe.lightcompressorlibrary.video.Mp4Movie.addTrack(Mp4Movie.kt:51)
        at com.abedelazizshe.lightcompressorlibrary.video.MP4Builder.addTrack(MP4Builder.kt:112)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.processAudio(Compressor.kt:445)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.start(Compressor.kt:404)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.compressVideo(Compressor.kt:160)
        at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:114)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-09-15 20:10:28.412 18517-18517/in.app.dev E/VideoCameraCapture: onSuccess:

**Comment by AbedElazizShe** [comment]
@vedraj360 sorry for late reply. This bug is fixed, i will release a new version soon. Thank you.

**Comment by AbedElazizShe** [comment]
Please check version 1.0.0, let me know if you still face the same issue.
