### ISSUE TITLE
Error while video compress

### ISSUE THREAD

**Issue by OlgaPetrusevich** [AbedElazizShe/LightCompressor#98]
Hello.
Thanks for your library.

Getting an error while compress video (UHD).
Samsung Galaxy A9

2021-10-25 12:07:30.982 15107-19349/? I/MediaCodec: failed to configure codec bacause of codec capacity
2021-10-25 12:07:30.982 15107-19349/? E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3
2021-10-25 12:07:30.984 15107-15235/? E/MediaCodec: configure failed with err 0xffffec77, resetting...
2021-10-25 12:07:30.989 15107-19350/? I/ACodec:  [OMX.qcom.video.decoder.avc] Now uninitialized
2021-10-25 12:07:30.989 15107-19350/? I/ACodec:  [] Now kWhatShutdownCompleted event : 8502
2021-10-25 12:07:30.989 15107-19349/? I/MediaCodec: Codec shutdown complete
2021-10-25 12:07:30.990 15107-15235/? I/ACodec:  [] Now uninitialized
2021-10-25 12:07:30.991 15107-19350/? I/ACodec: [] onAllocateComponent
2021-10-25 12:07:31.012 15107-19350/? I/ACodec: [OMX.qcom.video.decoder.avc] Now Loaded
2021-10-25 12:07:31.020 15107-15235/? E/Compressor: Error 0xffffec77
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.prepareDecoder(Compressor.kt:529)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.start(Compressor.kt:234)
        at com.abedelazizshe.lightcompressorlibrary.compressor.Compressor.compressVideo(Compressor.kt:160)
        at com.abedelazizshe.lightcompressorlibrary.VideoCompressor$startCompression$2.invokeSuspend(VideoCompressor.kt:114)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-10-25 12:07:31.956 15107-19342/? I/MediaCodec: setCodecState state : 0

**Comment by AbedElazizShe** [comment]
@OlgaPetrusevich thank you for opening this issue. The library does not support this format at the moment. I might add support in the near future.

Thank you.
